package org.mixtream.mixtreamwebmysql.service;

import org.mixtream.mixtreamwebmysql.model.AlbumTracks;
import org.mixtream.mixtreamwebmysql.repository.AlbumTracksRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 11/04/2021
*/
@Component
public class AlbumTracksService {

	private AlbumTracksRepository albumTracksRepository;

	@Autowired
	public AlbumTracksService(AlbumTracksRepository albumTracksRepository) {
		this.albumTracksRepository = albumTracksRepository;
	}

}
