package org.mixtream.mixtreamwebmysql.service;

import org.mixtream.mixtreamwebmysql.model.Play;
import org.mixtream.mixtreamwebmysql.repository.PlayRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 11/04/2021
*/
@Component
public class PlayService {

	private PlayRepository playRepository;

	@Autowired
	public PlayService(PlayRepository playRepository) {
		this.playRepository = playRepository;
	}

}
