package org.mixtream.mixtreamwebmysql.service;

import org.mixtream.mixtreamwebmysql.model.Playlist;
import org.mixtream.mixtreamwebmysql.repository.PlaylistRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 11/04/2021
*/
@Component
public class PlaylistService {

	private PlaylistRepository playlistRepository;

	@Autowired
	public PlaylistService(PlaylistRepository playlistRepository) {
		this.playlistRepository = playlistRepository;
	}

}
