package org.mixtream.mixtreamwebmysql.service;

import org.mixtream.mixtreamwebmysql.model.Role;
import org.mixtream.mixtreamwebmysql.repository.RoleRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 11/04/2021
*/
@Component
public class RoleService {

	private RoleRepository roleRepository;

	@Autowired
	public RoleService(RoleRepository roleRepository) {
		this.roleRepository = roleRepository;
	}

}
