package org.mixtream.mixtreamwebmysql.service;

import org.mixtream.mixtreamwebmysql.model.Track;
import org.mixtream.mixtreamwebmysql.repository.TrackRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 11/04/2021
*/
@Component
public class TrackService {

	private TrackRepository trackRepository;

	@Autowired
	public TrackService(TrackRepository trackRepository) {
		this.trackRepository = trackRepository;
	}

}
