package org.mixtream.mixtreamwebmysql.service;

import org.mixtream.mixtreamwebmysql.model.User;
import org.mixtream.mixtreamwebmysql.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 11/04/2021
*/
@Component
public class UserService {

	private UserRepository userRepository;

	@Autowired
	public UserService(UserRepository userRepository) {
		this.userRepository = userRepository;
	}

}
