package org.mixtream.mixtreamwebmysql.repository;

import org.mixtream.mixtreamwebmysql.model.Play;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.querydsl.QuerydslPredicateExecutor;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 11/04/2021
*/
@Repository
public interface PlayRepository extends JpaRepository<Play, Integer>, JpaSpecificationExecutor<Play>, QuerydslPredicateExecutor<Play> {

}
