package org.mixtream.mixtreamwebmysql.repository;

import org.mixtream.mixtreamwebmysql.model.UserRoles;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.querydsl.QuerydslPredicateExecutor;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 11/04/2021
*/
@Repository
public interface UserRolesRepository extends JpaRepository<UserRoles, Integer>, JpaSpecificationExecutor<UserRoles>, QuerydslPredicateExecutor<UserRoles> {

}
